#! /bin/bash

set -e

DIR=$(dirname "$(readlink -f "$0")")

if [ "$#" -eq 0 ]; then
    CMD=bash
else
    CMD="$@"
fi

IMG="$(docker build -q $DIR/.workbench)"

docker run --rm \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /etc/shadow:/etc/shadow:ro \
    -v "$HOME:$HOME" \
    -it $IMG sudo -u ${USER} -E sh -c "cd $DIR; HOME=$HOME $CMD"
