name: Publish release to dockerhub
on:
  release:
    types: [created]

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REPOSITORY: ${{ github.repository }}
  CONTAINER_IMAGE_PATH: ghcr.io/${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from release tag
        id: version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 4)"

      - name: Run tests
        run: |
          echo "Running tests..."
          VERSION=${{ steps.version.outputs.version }} ./tests/check-tag.sh
          echo "Tests passed"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{env.CONTAINER_IMAGE_PATH}}:${{ steps.tag.outputs.tag }}